# Data Shitery

In [1]:
# importing the required libraries
import os
import pandas as pd
import matplotlib.pyplot as plt

os.chdir( os.path.join("..", "..") )

from Code.src.modules.db_ops import *
from Code.src.modules.dataManager import DataManager
from Code.src.modules.eda import *

DM = DataManager()

In [2]:
# Importing the data
df_finalEnrollment = DM.get_data('EnrollmentFinalStatus', 'pkl', 'processed')
db_finalEnrollment = DM.get_data('EnrollmentFinalStatus', 'db', 'processed')

In [3]:
db_enrollment = DM.get_data('Enrollment', 'db', 'processed')
df_enrollment = DM.get_data('Enrollment', 'pkl', 'processed')

# Testing

## Take 2: Getting Final Status from latest snapshot only

In [4]:
# Final Snapshots

df = df_enrollment \
    .loc[
        ((df_enrollment['rec_ext_date'].dt.month.isin([2,9])) &
        (df_enrollment['rec_ext_date'].dt.day == 1)) |
        ((df_enrollment['rec_ext_date'].dt.month.isin([1,8])) &
        (df_enrollment['rec_ext_date'].dt.day == 15))
    ]

df.head().T
df[['reg_term_code', 'stu_id', 'crs']]
# df.to_csv( os.path.join('Data', '02_processed', 'final_snapshot.csv') )
# df.to_pickle( os.path.join('Data', '02_processed', 'final_snapshot.pkl') )

# db = ConnectDB( os.path.join("Data", "02_processed", "final_snapshot.db") )
# df.to_sql("FinalSnapshot", db.connection, if_exists="replace", index=False)

       reg_term_code    stu_id       crs
13924         201770   CEC2640    CS 504
13925         201770   CEC2640  DAEN 690
13926         201770   CEC3286  INFS 640
13927         201770   CEC3289   SWE 619
13928         201770    CEC865  CEIE 639
...              ...       ...       ...
318574        202310  CEC30889   AIT 614
318575        202310  CEC11679  CEIE 605
318576        202310  CEC11679  CEIE 639
318577        202310  CEC11679  CEIE 795
318578        202310  CEC29531    CS 530

[82851 rows x 3 columns]

In [5]:
# Getting the latest re_ext_date for each Registration Term
db_enrollment.runQuery(""" --sql
    SELECT reg_term_desc, rec_ext_date
    FROM enrollment4EDA
    WHERE
        reg_term_desc IN ('Fall 2021', 'Spring 2022')
    GROUP BY reg_term_desc, rec_ext_date
    ORDER BY reg_term_code, rec_ext_date
""")

   reg_term_desc         rec_ext_date
0      Fall 2021  2021-05-01 00:00:00
1      Fall 2021  2021-05-15 00:00:00
2      Fall 2021  2021-06-01 00:00:00
3      Fall 2021  2021-06-15 00:00:00
4      Fall 2021  2021-07-01 00:00:00
5      Fall 2021  2021-07-15 00:00:00
6      Fall 2021  2021-08-01 00:00:00
7      Fall 2021  2021-08-15 00:00:00
8      Fall 2021  2021-09-01 00:00:00
9      Fall 2021  2021-09-15 00:00:00
10   Spring 2022  2021-11-04 00:00:00
11   Spring 2022  2021-11-15 00:00:00
12   Spring 2022  2021-12-01 00:00:00
13   Spring 2022  2021-12-15 00:00:00
14   Spring 2022  2022-01-01 00:00:00
15   Spring 2022  2022-01-15 00:00:00
16   Spring 2022  2022-02-01 00:00:00
17   Spring 2022  2022-02-15 00:00:00

In [6]:
# Not a reliable approach for fetching the latest enrollment info

# # Fetching the final snapshot of registration data for each semester
# df = db_enrollment.runQuery(""" --sql
#     SELECT *
#     FROM enrollment4EDA
#     WHERE
#         rec_ext_date IN (
#             SELECT MAX(rec_ext_date) AS LatestSnapshot
#             FROM enrollment4EDA
#             GROUP BY reg_term_desc
#             ORDER BY reg_term_code)
# """)

# # Exporting the final snapshot
# df.to_csv( os.path.join('Data', '02_processed', 'final_snapshot.csv') )
# df.to_pickle( os.path.join('Data', '02_processed', 'final_snapshot.pkl') )

# db = ConnectDB( os.path.join("Data", "02_processed", "final_snapshot.db") )
# df.to_sql("FinalSnapshot", db.connection, if_exists="replace", index=False)

# df.info()

In [7]:
# Checking if data is consistent
df \
    .loc[
        (df['stu_prog_desc'] == "MS Data Analytics Engineering") &
        #(df['stu_admit_term_desc'] == "Fall 2021") &
        (df['stu_visa'] == "F1 Visa") &
        (df['reg_status'].isin(["**Web Registered**", "Wait Listed", "**Registered**"]))
    ] \
        .groupby(['stu_new_ret', 'stu_id', 'reg_term_code', 'stu_admit_term_desc', 'reg_term_desc']) \
            .agg({'rec_id': 'count', 'crs': 'unique'}) \
                .reset_index() \
                    .sort_values(['rec_id']).head(60)

,stu_new_ret,stu_id,reg_term_code,stu_admit_term_desc,reg_term_desc,rec_id,crs
0,N,CEC10012,201770,Fall 2016,Fall 2017,0,NaN
3443284,R,CEC20850,202010,Spring 2021,Fall 2021,0,NaN
3443283,R,CEC20850,202010,Spring 2021,Fall 2020,0,NaN
3443282,R,CEC20850,202010,Spring 2021,Fall 2019,0,NaN
3443281,R,CEC20850,202010,Spring 2021,Fall 2018,0,NaN
3443280,R,CEC20850,202010,Spring 2021,Fall 2017,0,NaN
3443279,R,CEC20850,202010,Spring 2020 - COVID-19,Spring 2023,0,NaN
3443278,R,CEC20850,202010,Spring 2020 - COVID-19,Spring 2022,0,NaN
3443277,R,CEC20850,202010,Spring 2020 - COVID-19,Spring 2021,0,NaN
3443276,R,CEC20850,202010,Spring 2020 - COVID-19,Spring 2020 - COVID-19,0,NaN
3443275,R,CEC20850,202010,Spring 2020 - COVID-19,Spring 2019,0,NaN
3443274,R,CEC20850,202010,Spring 2020 - COVID-19,Spring 2018,0,NaN
3443273,R,CEC20850,202010,Spring 2020 - COVID-19,Fall 2022,0,NaN
3443272,R,CEC20850,202010,Spring 2020 - COVID-19,Fall 2021,0,NaN
3443271,R,CEC20850,202010,Spring 2020 - COVID-19,Fall 2020,0,NaN
3443270,R,CEC20850,202010,Spring 2020 - COVID-19,Fall 2019,0,NaN
3443285,R,CEC20850,202010,Spring 2021,Fall 2022,0,NaN
3443286,R,CEC20850,202010,Spring 2021,Spring 2018,0,NaN
3443287,R,CEC20850,202010,Spring 2021,Spring 2019,0,NaN
3443288,R,CEC20850,202010,Spring 2021,Spring 2020 - COVID-19,0,NaN
3443304,R,CEC20850,202010,Spring 2023,Fall 2017,0,NaN
3443303,R,CEC20850,202010,Spring 2022,Spring 2023,0,NaN
3443302,R,CEC20850,202010,Spring 2022,Spring 2022,0,NaN
3443301,R,CEC20850,202010,Spring 2022,Spring 2021,0,NaN
3443300,R,CEC20850,202010,Spring 2022,Spring 2020 - COVID-19,0,NaN
3443299,R,CEC20850,202010,Spring 2022,Spring 2019,0,NaN
3443298,R,CEC20850,202010,Spring 2022,Spring 2018,0,NaN
3443269,R,CEC20850,202010,Spring 2020 - COVID-19,Fall 2018,0,NaN
3443297,R,CEC20850,202010,Spring 2022,Fall 2022,0,NaN
3443295,R,CEC20850,202010,Spring 2022,Fall 2020,0,NaN
3443294,R,CEC20850,202010,Spring 2022,Fall 2019,0,NaN
3443293,R,CEC20850,202010,Spring 2022,Fall 2018,0,NaN
3443292,R,CEC20850,202010,Spring 2022,Fall 2017,0,NaN
3443291,R,CEC20850,202010,Spring 2021,Spring 2023,0,NaN
3443290,R,CEC20850,202010,Spring 2021,Spring 2022,0,NaN
3443289,R,CEC20850,202010,Spring 2021,Spring 2021,0,NaN
3443296,R,CEC20850,202010,Spring 2022,Fall 2021,0,NaN
3443305,R,CEC20850,202010,Spring 2023,Fall 2018,0,NaN
3443268,R,CEC20850,202010,Spring 2020 - COVID-19,Fall 2017,0,NaN
3443266,R,CEC20850,202010,Spring 2019,Spring 2022,0,NaN
3443245,R,CEC20850,202010,Spring 2018,Fall 2018,0,NaN
3443244,R,CEC20850,202010,Spring 2018,Fall 2017,0,NaN
3443243,R,CEC20850,202010,Spring 2017,Spring 2023,0,NaN
3443242,R,CEC20850,202010,Spring 2017,Spring 2022,0,NaN
3443241,R,CEC20850,202010,Spring 2017,Spring 2021,0,NaN
3443240,R,CEC20850,202010,Spring 2017,Spring 2020 - COVID-19,0,NaN
3443239,R,CEC20850,202010,Spring 2017,Spring 2019,0,NaN
3443238,R,CEC20850,202010,Spring 2017,Spring 2018,0,NaN
3443237,R,CEC20850,202010,Spring 2017,Fall 2022,0,NaN
3443236,R,CEC20850,202010,Spring 2017,Fall 2021,0,NaN
3443235,R,CEC20850,202010,Spring 2017,Fall 2020,0,NaN
3443234,R,CEC20850,202010,Spring 2017,Fall 2019,0,NaN
3443233,R,CEC20850,202010,Spring 2017,Fall 2018,0,NaN
3443232,R,CEC20850,202010,Spring 2017,Fall 2017,0,NaN
3443231,R,CEC20850,202010,Spring 2016,Spring 2023,0,NaN
3443246,R,CEC20850,202010,Spring 2018,Fall 2019,0,NaN
3443247,R,CEC20850,202010,Spring 2018,Fall 2020,0,NaN
3443248,R,CEC20850,202010,Spring 2018,Fall 2021,0,NaN
3443249,R,CEC20850,202010,Spring 2018,Fall 2022,0,NaN
3443265,R,CEC20850,202010,Spring 2019,Spring 2021,0,NaN

In [8]:
# Getting total course registration for each student
df \
    .loc[
        (df['stu_prog_desc'] == "MS Data Analytics Engineering") &
        (df['stu_admit_term_desc'] == "Fall 2021") &
        (df['stu_visa'] == "F1 Visa") &
        (df['reg_status'] in ["**Web Registered**", "Wait Listed", "**Registered**"])
    ] \
        .groupby('stu_id', as_index=False) \
            .agg({'crs':'count'}) \
                .sort_values('crs', ascending=True) \
                    .groupby('crs', as_index=False) \
                        .agg({'stu_id':'count'}) \
                            .rename(columns={'stu_id':'count'})

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
# Getting the latest snapshot for each Registration Term
df = db_enrollment.runQuery(""" --sql
    SELECT stu_id, COUNT(*) AS Count
    FROM enrollment4EDA
    WHERE
        rec_ext_date IN (
            SELECT MAX(rec_ext_date) AS LatestSnapshot
            FROM enrollment4EDA
            GROUP BY reg_term_desc
            ORDER BY reg_term_code)
        AND stu_prog_desc = "MS Data Analytics Engineering"
        AND stu_admit_term_desc = "Fall 2021"
        AND stu_visa = "F1 Visa"
    GROUP BY stu_id
    ORDER BY Count
""")

df.head(60)

      stu_id  Count
0   CEC27550      1
1   CEC28239      1
2   CEC26131      2
3   CEC26913      2
4   CEC27189      2
5   CEC27486      2
6   CEC27628      2
7   CEC27747      2
8   CEC23829      3
9   CEC23919      3
10  CEC27527      3
11  CEC27532      3
12  CEC27539      3
13  CEC27554      3
14  CEC27762      3
15  CEC25931      4
16  CEC27796      4
17  CEC20464      6
18  CEC21163      6
19  CEC24306      6
20  CEC27426      6
21  CEC27795      6
22  CEC20602      7
23   CEC3743      7
24  CEC24070      8
25  CEC26017      8
26  CEC20709      9
27  CEC20941      9
28  CEC23440      9
29  CEC24740      9
30  CEC26229      9
31  CEC26469      9
32  CEC27049      9
33  CEC27171      9
34  CEC27219      9
35  CEC27306      9
36  CEC27320      9
37  CEC27503      9
38  CEC27525      9
39  CEC27534      9
40  CEC27592      9
41  CEC27618      9
42  CEC27725      9
43  CEC10635     10
44  CEC16791     10
45  CEC20449     10
46  CEC21494     10
47  CEC21919     10
48  CEC22410     10
49  CEC22663     10
50  CEC22781     10
51  CEC22922     10
52  CEC22942     10
53  CEC23268     10
54  CEC23281     10
55  CEC23437     10
56  CEC23576     10
57  CEC23612     10
58  CEC23760     10
59  CEC23791     10

## Getting Final Enrollment Data

In [ ]:
# This Student is nuts. What's wrong with them? 3-3-3-1 pattern??
db_enrollment.runQuery(""" --sql
    SELECT rec_id, stu_admit_term_desc, stu_id, stu_prog_desc, reg_status_date, reg_term_desc, crs, crs_sect, reg_status, rec_ext_date
FROM enrollment4EDA
WHERE
    stu_id = "CEC25006"
    AND reg_term_desc = "Fall 2022"
ORDER BY
    reg_term_code, rec_ext_date, crs, reg_status_date ;
""").head(60)

NameError: name 'db_enrollment' is not defined

In [74]:
#  Final Enrollment for the student
db_finalEnrollment.runQuery(""" --sql
    SELECT rec_id, stu_admit_term_desc, stu_id, stu_prog_desc, reg_status_date, reg_term_desc, crs, reg_status, rec_ext_date
    FROM enrollmentFinalStatus
    WHERE
        stu_id = "CEC28311"
""")

,rec_id,stu_admit_term_desc,stu_id,stu_prog_desc,reg_status_date,reg_term_desc,crs,reg_status,rec_ext_date
0,216223,Spring 2022,CEC28311,MS Computer Science,2021-11-03 00:00:00,Spring 2022,CS 531,**Web Registered**,2022-01-01 00:00:00
1,216754,Spring 2022,CEC28311,MS Computer Science,2021-11-07 00:00:00,Spring 2022,CS 504,**Web Registered**,2022-01-01 00:00:00
2,216755,Spring 2022,CEC28311,MS Computer Science,2021-11-07 00:00:00,Spring 2022,CS 530,**Web Registered**,2022-01-01 00:00:00
3,218234,Spring 2022,CEC28311,MS Computer Science,2022-01-14 00:00:00,Spring 2022,CS 540,**Web Registered**,2022-01-15 00:00:00
4,218235,Spring 2022,CEC28311,MS Computer Science,2022-01-14 00:00:00,Spring 2022,CS 571,Wait Listed,2022-01-15 00:00:00
5,218236,Spring 2022,CEC28311,MS Computer Science,2022-01-14 00:00:00,Spring 2022,CS 583,Wait Listed,2022-01-15 00:00:00
6,222921,Spring 2022,CEC28311,MS Computer Science,2022-01-22 00:00:00,Spring 2022,SWE 622,**Web Registered**,2022-02-01 00:00:00
7,223242,Spring 2022,CEC28311,MS Computer Science,2022-01-25 00:00:00,Spring 2022,CS 550,**Web Registered**,2022-02-01 00:00:00
8,223637,Spring 2022,CEC28311,MS Computer Science,2022-01-30 00:00:00,Spring 2022,SWE 621,Wait Listed,2022-02-01 00:00:00
9,232635,Spring 2022,CEC28311,MS Computer Science,2021-11-03 00:00:00,Spring 2022,CS 580,**Web Registered**,2021-11-04 00:00:00
10,253201,Spring 2022,CEC28311,MS Computer Science,2022-05-08 00:00:00,Fall 2022,CS 555,**Web Registered**,2022-05-15 00:00:00
11,253202,Spring 2022,CEC28311,MS Computer Science,2022-05-08 00:00:00,Fall 2022,INFS 622,**Web Registered**,2022-05-15 00:00:00
12,263910,Spring 2022,CEC28311,MS Computer Science,2022-06-02 00:00:00,Fall 2022,INFS 612,**Web Registered**,2022-06-15 00:00:00
13,268699,Spring 2022,CEC28311,MS Computer Science,2022-06-18 00:00:00,Fall 2022,CS 580,**Web Registered**,2022-07-01 00:00:00
14,275733,Spring 2022,CEC28311,MS Computer Science,2022-07-02 00:00:00,Fall 2022,INFS 740,**Web Registered**,2022-07-15 00:00:00
15,275832,Spring 2022,CEC28311,MS Computer Science,2022-07-06 00:00:00,Fall 2022,CS 583,Wait Listed,2022-07-15 00:00:00
16,281028,Spring 2022,CEC28311,MS Computer Science,2022-07-18 00:00:00,Fall 2022,SWE 642,Wait Listed,2022-08-01 00:00:00
17,287495,Spring 2022,CEC28311,MS Software Engineering,2022-08-12 00:00:00,Fall 2022,SWE 637,**Web Registered**,2022-08-15 00:00:00
18,287967,Spring 2022,CEC28311,MS Software Engineering,2022-08-04 00:00:00,Fall 2022,SWE 625,**Web Registered**,2022-08-15 00:00:00
19,288184,Spring 2022,CEC28311,MS Software Engineering,2022-08-08 00:00:00,Fall 2022,CS 584,**Web Registered**,2022-08-15 00:00:00
20,288290,Spring 2022,CEC28311,MS Software Engineering,2022-08-09 00:00:00,Fall 2022,SWE 645,Wait Listed,2022-08-15 00:00:00
21,292970,Spring 2022,CEC28311,MS Software Engineering,2022-08-23 00:00:00,Fall 2022,SWE 632,**Web Registered**,2022-09-01 00:00:00
22,293066,Spring 2022,CEC28311,MS Software Engineering,2022-08-24 00:00:00,Fall 2022,SWE 621,**Web Registered**,2022-09-01 00:00:00
23,300624,Spring 2022,CEC28311,MS Software Engineering,2022-11-01 00:00:00,Spring 2023,SWE 619,**Web Registered**,2023-01-01 00:00:00
24,300625,Spring 2022,CEC28311,MS Software Engineering,2022-11-01 00:00:00,Spring 2023,SWE 795,**Web Registered**,2023-01-01 00:00:00
25,300626,Spring 2022,CEC28311,MS Software Engineering,2022-11-01 00:00:00,Spring 2023,SWE 642,Wait Listed,2023-01-01 00:00:00
26,300627,Spring 2022,CEC28311,MS Software Engineering,2022-11-01 00:00:00,Spring 2023,SWE 645,Wait Listed,2023-01-01 00:00:00
27,303757,Spring 2022,CEC28311,MS Software Engineering,2022-11-03 00:00:00,Spring 2023,INFS 622,**Web Registered**,2023-01-01 00:00:00
28,314244,Spring 2022,CEC28311,MS Software Engineering,2023-01-24 00:00:00,Spring 2023,SWE 625,**Web Registered**,2023-02-01 00:00:00

In [46]:
# Testing if the way we created the final enrollment status is correct
db_enrollment.runQuery(""" --sql
    SELECT reg_term_desc, stu_admit_term_desc, stu_id, crs, MAX(reg_status_date) as final_reg_date, reg_status
    FROM enrollment4EDA
    WHERE
        stu_visa = "F1 Visa"
    GROUP BY reg_term_desc, stu_id, crs
    ORDER BY reg_term_code DESC, stu_id, final_reg_date, crs;
""").head(60)

,reg_term_desc,stu_admit_term_desc,stu_id,crs,final_reg_date,reg_status
0,Spring 2023,Fall 2021,CEC10635,DAEN 690,2022-12-20 00:00:00,**Web Registered**
1,Spring 2023,Spring 2021,CEC11382,SYST 514,2022-11-14 00:00:00,**Web Registered**
2,Spring 2023,Spring 2021,CEC11382,SYST 699,2023-01-04 00:00:00,**Web Registered**
3,Spring 2023,Fall 2021,CEC14339,ECE 555,2023-01-15 00:00:00,**Web Registered**
4,Spring 2023,Fall 2021,CEC14339,ECE 615,2023-01-15 00:00:00,**Web Registered**
5,Spring 2023,Fall 2021,CEC14339,ECE 612,2023-01-24 00:00:00,**Web Registered**
6,Spring 2023,Fall 2021,CEC14339,ECE 698,2023-01-30 00:00:00,**Web Registered**
7,Spring 2023,Fall 2021,CEC14339,ECE 795,2023-01-30 00:00:00,**Web Registered**
8,Spring 2023,Fall 2021,CEC14339,ECE 797,2023-01-30 00:00:00,**Web Registered**
9,Spring 2023,Spring 2022,CEC15381,CS 663,2022-11-01 00:00:00,**Web Registered**
10,Spring 2023,Spring 2022,CEC15381,CS 682,2022-11-01 00:00:00,**Web Registered**
11,Spring 2023,Spring 2022,CEC15381,CS 747,2022-11-01 00:00:00,**Web Registered**
12,Spring 2023,Spring 2022,CEC15381,SWE 645,2022-11-01 00:00:00,**Web Registered**
13,Spring 2023,Fall 2022,CEC16707,ECE 552,2022-11-01 00:00:00,**Web Registered**
14,Spring 2023,Fall 2022,CEC16707,CS 504,2022-12-01 00:00:00,**Web Registered**
15,Spring 2023,Fall 2022,CEC16707,AIT 614,2022-12-03 00:00:00,Wait Listed
16,Spring 2023,Fall 2022,CEC16707,GBUS 738,2022-12-08 00:00:00,**Web Registered**
17,Spring 2023,Fall 2022,CEC16707,GBUS 744,2022-12-29 00:00:00,**Web Registered**
18,Spring 2023,Spring 2022,CEC16727,DAEN 690,2022-11-01 00:00:00,**Web Registered**
19,Spring 2023,Spring 2022,CEC16727,GBUS 744,2023-01-04 00:00:00,**Registered**
20,Spring 2023,Spring 2022,CEC16727,GBUS 720,2023-01-23 00:00:00,**Web Registered**
21,Spring 2023,Fall 2021,CEC16791,DAEN 690,2022-11-01 00:00:00,**Web Registered**
22,Spring 2023,Fall 2021,CEC16970,ECE 611,2022-11-01 00:00:00,**Web Registered**
23,Spring 2023,Fall 2021,CEC16970,ECE 618,2022-11-01 00:00:00,**Web Registered**
24,Spring 2023,Fall 2021,CEC16970,ECE 797,2023-01-26 00:00:00,**Web Registered**
25,Spring 2023,Spring 2022,CEC19524,ECE 552,2022-11-01 00:00:00,**Web Registered**
26,Spring 2023,Spring 2022,CEC19524,ECE 618,2022-11-01 00:00:00,**Web Registered**
27,Spring 2023,Spring 2022,CEC19524,ECE 795,2022-11-01 00:00:00,**Web Registered**
28,Spring 2023,Spring 2022,CEC19524,ECE 797,2022-11-01 00:00:00,**Web Registered**
29,Spring 2023,Spring 2022,CEC19858,AIT 622,2022-11-01 00:00:00,**Web Registered**
30,Spring 2023,Spring 2022,CEC19858,GBUS 738,2022-11-01 00:00:00,**Web Registered**
31,Spring 2023,Spring 2022,CEC19858,GBUS 744,2022-11-17 00:00:00,**Web Registered**
32,Spring 2023,Spring 2022,CEC19858,HAP 720,2023-01-24 00:00:00,**Web Registered**
33,Spring 2023,Spring 2022,CEC20236,AIT 655,2022-11-02 00:00:00,**Web Registered**
34,Spring 2023,Spring 2022,CEC20236,AIT 670,2022-11-02 00:00:00,**Web Registered**
35,Spring 2023,Spring 2022,CEC20236,AIT 690,2022-11-02 00:00:00,**Web Registered**
36,Spring 2023,Spring 2022,CEC20236,AIT 677,2023-01-09 00:00:00,**Web Registered**
37,Spring 2023,Spring 2022,CEC20236,AIT 679,2023-01-20 00:00:00,**Web Registered**
38,Spring 2023,Spring 2022,CEC20236,AIT 614,2023-01-22 00:00:00,**Web Registered**
39,Spring 2023,Spring 2022,CEC20391,DAEN 690,2022-11-01 00:00:00,**Web Registered**
40,Spring 2023,Fall 2021,CEC20449,DAEN 690,2022-11-01 00:00:00,**Web Registered**
41,Spring 2023,Fall 2022,CEC20676,AIT 580,2022-11-01 00:00:00,**Web Registered**
42,Spring 2023,Fall 2022,CEC20676,AIT 736,2022-11-01 00:00:00,**Web Registered**
43,Spring 2023,Fall 2022,CEC20676,CS 504,2022-11-01 00:00:00,**Web Registered**
44,Spring 2023,Fall 2022,CEC20676,GBUS 738,2022-11-01 00:00:00,**Web Registered**
45,Spring 2023,Spring 2022,CEC20677,SWE 637,2022-11-01 00:00:00,**Web Registered**
46,Spring 2023,Spring 2022,CEC20677,SWE 681,2022-11-01 00:00:00,**Web Registered**
47,Spring 2023,Spring 2022,CEC20677,SWE 632,2022-11-02 00:00:00,**Web Registered**
48,Spring 2023,Spring 2022,CEC20677,CS 531,2022-12-18 00:00:00,**Web Registered**
49,Spring 2023,Fall 2021,CEC21488,CS 688,2022-11-01 00:00:00,**Web Registered**
50,Spring 2023,Fall 2021,CEC21488,CS 695,2022-11-01 00:00:00,**Web Registered**
51,Spring 2023,Fall 2021,CEC21488,CS 795,2022-11-01 00:00:00,**Web Registered**
52,Spring 2023,Fall 2021,CEC21494,DAEN 690,2022-11-01 00:00:00,**Web Registered**
53,Spring 2023,Fall 2021,CEC21676,CS 663,2022-11-01 00:00:00,**Web Registered**
54,Spring 2023,Fall 2021,CEC21676,CS 678,2022-11-01 00:00:00,**Web Registered**
55,Spring 2023,Fall 2021,CEC21676,CS 695,2022-11-01 00:00:00,**Web Registered**
56,Spring 2023,Fall 2021,CEC21802,ISA 562,2022-11-01 00:00:00,**Web Registered**
57,Spring 2023,Fall 2021,CEC21802,ISA 564,2022-11-01 00:00:00,**Web Registered**
58,Spring 2023,Spring 2020 - COVID-19,CEC21821,CS 799,2023-01-18 00:00:00,**Web Registered**
59,Spring 2023,Fall 2021,CEC21863,DAEN 690,2022-11-01 00:00:00,**Web Registered**

In [11]:
# Checking number of classes registered by International Students
df = db_finalEnrollment.runQuery(""" --sql
    SELECT stu_id, COUNT(DISTINCT crs) as num_crs
    FROM enrollmentFinalStatus
    WHERE
                stu_visa = "F1 Visa"
        AND     stu_prog_desc = "MS Data Analytics Engineering"
        AND     reg_status IN ("**Web Registered**", "**Registered**")
        AND     stu_admit_term_year = reg_term_year
        AND     stu_admit_term_year > 2020
    GROUP BY stu_id
    ORDER BY num_crs DESC;
""")

df
# df.groupby('num_crs').count()
# df.plot.hist(bins=100, figsize=(10, 5))

       stu_id  num_crs
0    CEC24702       12
1    CEC22693       12
2    CEC21786       12
3    CEC28750       11
4    CEC22896       11
..        ...      ...
654  CEC28058        1
655  CEC27607        1
656  CEC27550        1
657  CEC27460        1
658  CEC25474        1

[659 rows x 2 columns]

## Enrollment Numbers for International Students

In [17]:
query1 = db_finalEnrollment.runQuery(""" --sql
    SELECT
        stu_admit_term_desc, reg_term_desc,
        COUNT(DISTINCT stu_id) AS 'Total International Students Admitted',
        SUM(CASE WHEN crs = 'AIT 580' THEN 1 ELSE 0 END) AS 'AIT 580',
        SUM(CASE WHEN crs = 'CS 504' THEN 1 ELSE 0 END) AS 'CS 504',
        SUM(CASE WHEN crs = 'STAT 515' THEN 1 ELSE 0 END) AS 'STAT 515',
        SUM(CASE WHEN crs = 'OR 531' THEN 1 ELSE 0 END) AS 'OR 531'
    FROM EnrollmentFinalStatus
    WHERE
                stu_visa = 'F1 Visa'
        AND     stu_prog_desc = 'MS Data Analytics Engineering'
        AND     stu_admit_term_year > 2017
        AND     reg_status IN ("**Web Registered**", "Wait Listed", "**Registered**")
    GROUP BY
        stu_admit_term_desc, reg_term_desc
    ORDER BY
        stu_admit_term_code, reg_term_code
""")

query1

,stu_admit_term_desc,reg_term_desc,Total International Students Admitted,AIT 580,CS 504,STAT 515,OR 531
0,Spring 2018,Spring 2018,40,21,24,22,18
1,Spring 2018,Fall 2018,41,5,12,2,3
2,Spring 2018,Spring 2019,36,1,8,0,1
3,Spring 2018,Fall 2019,13,0,1,0,0
4,Spring 2018,Spring 2020 - COVID-19,1,0,0,0,0
5,Fall 2018,Fall 2018,83,63,41,58,51
6,Fall 2018,Spring 2019,78,11,50,8,11
7,Fall 2018,Fall 2019,79,1,12,2,2
8,Fall 2018,Spring 2020 - COVID-19,59,0,0,0,0
9,Fall 2018,Fall 2020,3,0,0,0,0
10,Fall 2018,Spring 2021,1,0,0,0,0
11,Spring 2019,Spring 2019,48,28,23,33,24
12,Spring 2019,Fall 2019,45,3,17,0,7
13,Spring 2019,Spring 2020 - COVID-19,37,0,1,1,2
14,Spring 2019,Fall 2020,19,0,0,0,0
15,Fall 2019,Fall 2019,78,59,46,59,51
16,Fall 2019,Spring 2020 - COVID-19,73,13,33,3,21
17,Fall 2019,Fall 2020,68,2,11,1,3
18,Fall 2019,Spring 2021,56,0,0,0,1
19,Spring 2020 - COVID-19,Spring 2020 - COVID-19,66,43,41,52,44
20,Spring 2020 - COVID-19,Fall 2020,61,2,22,2,22
21,Spring 2020 - COVID-19,Spring 2021,55,0,3,0,4
22,Spring 2020 - COVID-19,Fall 2021,35,0,0,0,1
23,Spring 2020 - COVID-19,Spring 2022,2,0,0,0,0
24,Fall 2020,Fall 2020,53,32,34,36,27
25,Fall 2020,Spring 2021,31,3,2,0,3
26,Fall 2020,Fall 2021,22,0,0,0,2
27,Fall 2020,Spring 2022,6,0,0,0,0
28,Fall 2020,Fall 2022,2,0,0,0,0
29,Spring 2021,Spring 2021,82,68,64,65,41
30,Spring 2021,Fall 2021,78,7,10,22,52
31,Spring 2021,Spring 2022,74,1,1,0,3
32,Spring 2021,Fall 2022,48,0,0,0,0
33,Fall 2021,Fall 2021,149,131,116,132,94
34,Fall 2021,Spring 2022,118,21,46,13,51
35,Fall 2021,Fall 2022,110,1,12,0,0
36,Fall 2021,Spring 2023,86,0,1,0,0
37,Spring 2022,Spring 2022,119,112,82,113,76
38,Spring 2022,Fall 2022,92,5,43,3,29
39,Spring 2022,Spring 2023,89,0,1,0,3
40,Fall 2022,Fall 2022,189,183,89,186,159
41,Fall 2022,Spring 2023,165,16,118,6,34
42,Spring 2023,Spring 2023,143,127,67,140,122

In [26]:
db_finalEnrollment.runQuery(""" --sql
    SELECT stu_admit_term_desc, COUNT(DISTINCT stu_id) AS 'Incoming Students',3*COUNT(DISTINCT stu_id) AS 'Expected Course Registrations'
    FROM EnrollmentFinalStatus
    WHERE
                stu_visa = 'F1 Visa'
        AND     stu_prog_desc = 'MS Data Analytics Engineering'
        AND     stu_admit_term_year > 2017
        AND     reg_status IN ("**Web Registered**", "**Registered**")
    GROUP BY stu_admit_term_desc
    ORDER BY stu_admit_term_code
""")

       stu_admit_term_desc  Incoming Students  Expected Course Registrations
0              Spring 2018                 44                            132
1                Fall 2018                 89                            267
2              Spring 2019                 50                            150
3                Fall 2019                 83                            249
4   Spring 2020 - COVID-19                 69                            207
5                Fall 2020                 54                            162
6              Spring 2021                 85                            255
7                Fall 2021                148                            444
8              Spring 2022                118                            354
9                Fall 2022                190                            570
10             Spring 2023                142                            426

In [25]:
db_finalEnrollment.runQuery(""" --sql
    SELECT stu_admit_term_desc, reg_term_desc, COUNT(stu_id) AS 'Total Course Registrations'
    FROM EnrollmentFinalStatus
    WHERE
                stu_visa = 'F1 Visa'
        AND     stu_prog_desc = 'MS Data Analytics Engineering'
        AND     stu_admit_term_year > 2017
        AND     reg_status IN ("**Web Registered**", "**Registered**")
    GROUP BY stu_admit_term_desc, reg_term_desc
    ORDER BY stu_admit_term_code, reg_term_code
""")

       stu_admit_term_desc           reg_term_desc  Total Course Registrations
0              Spring 2018             Spring 2018                         133
1              Spring 2018               Fall 2018                         187
2              Spring 2018             Spring 2019                         119
3              Spring 2018               Fall 2019                          37
4              Spring 2018  Spring 2020 - COVID-19                           2
5                Fall 2018               Fall 2018                         317
6                Fall 2018             Spring 2019                         315
7                Fall 2018               Fall 2019                         324
8                Fall 2018  Spring 2020 - COVID-19                         154
9                Fall 2018               Fall 2020                           4
10               Fall 2018             Spring 2021                           1
11             Spring 2019             Spring 2019                         169
12             Spring 2019               Fall 2019                         196
13             Spring 2019  Spring 2020 - COVID-19                         139
14             Spring 2019               Fall 2020                          42
15               Fall 2019               Fall 2019                         289
16               Fall 2019  Spring 2020 - COVID-19                         366
17               Fall 2019               Fall 2020                         344
18               Fall 2019             Spring 2021                         145
19  Spring 2020 - COVID-19  Spring 2020 - COVID-19                         247
20  Spring 2020 - COVID-19               Fall 2020                         279
21  Spring 2020 - COVID-19             Spring 2021                         229
22  Spring 2020 - COVID-19               Fall 2021                          73
23  Spring 2020 - COVID-19             Spring 2022                           3
24               Fall 2020               Fall 2020                         201
25               Fall 2020             Spring 2021                         146
26               Fall 2020               Fall 2021                          77
27               Fall 2020             Spring 2022                          16
28               Fall 2020               Fall 2022                           3
29             Spring 2021             Spring 2021                         307
30             Spring 2021               Fall 2021                         373
31             Spring 2021             Spring 2022                         308
32             Spring 2021               Fall 2022                         165
33               Fall 2021               Fall 2021                         507
34               Fall 2021             Spring 2022                         488
35               Fall 2021               Fall 2022                         495
36               Fall 2021             Spring 2023                         150
37             Spring 2022             Spring 2022                         369
38             Spring 2022               Fall 2022                         419
39             Spring 2022             Spring 2023                         307
40               Fall 2022               Fall 2022                         629
41               Fall 2022             Spring 2023                         616
42             Spring 2023             Spring 2023                         465