In [3]:
# importing the required libraries
import os
import pandas as pd
import matplotlib.pyplot as plt

os.chdir( os.path.join("..", "..", "..") )

from Code.src.modules.db_ops import *

In [9]:
# Importing the data
db_enrollment = ConnectDB( os.path.join("Data", "02_processed", "enrollment4EDA.db") )
df_enrollment = pd.read_pickle( os.path.join("Data", "02_processed", "enrollment.pkl") )

## Final Enrollment Status of all Students throughout his/her time at the University

In [6]:
df_enrollmentFinalStatus = db_enrollment.runQuery("""
    SELECT rec_id, reg_term_code, reg_term_desc, stu_id, crs, MAX(reg_status_date) as final_reg_date, reg_status
    FROM enrollment4EDA
    GROUP BY reg_term_code, reg_term_desc, stu_id, crs
    ORDER BY final_reg_date;
""")

df_enrollmentFinalStatus

,rec_id,reg_term_code,reg_term_desc,stu_id,crs,final_reg_date,reg_status
0,21,201770,Fall 2017,CEC100,AIT 622,2017-04-11 00:00:00,**Web Registered**
1,614,201770,Fall 2017,CEC10011,TCOM 515,2017-04-11 00:00:00,**Web Registered**
2,615,201770,Fall 2017,CEC10011,TCOM 631,2017-04-11 00:00:00,**Web Registered**
3,617,201770,Fall 2017,CEC10012,OR 538,2017-04-11 00:00:00,**Web Registered**
4,618,201770,Fall 2017,CEC10012,SYST 542,2017-04-11 00:00:00,**Web Registered**
...,...,...,...,...,...,...,...
59404,323682,202310,Spring 2023,CEC23433,CEC 794,2023-02-09 00:00:00,**Registered**
59405,323683,202310,Spring 2023,CEC26826,CS 678,2023-02-09 00:00:00,**Registered**
59406,323685,202310,Spring 2023,CEC27498,INFS 580,2023-02-09 00:00:00,**Registered**
59407,323684,202310,Spring 2023,CEC27967,CS 504,2023-02-09 00:00:00,**Web Registered**
59408,323686,202310,Spring 2023,CEC28062,CEC 794,2023-02-09 00:00:00,**Registered**

In [20]:
df_enrollmentFinalStatus = df_enrollment[df_enrollment["rec_id"].isin(df_enrollmentFinalStatus["rec_id"])]

In [22]:
df_enrollmentFinalStatus

,rec_id,rec_ext_date,file_name,file_index,reg_term_code,reg_term_year,reg_term_name,reg_term_desc,stu_id,stu_deg_level,...,crs_type,crs_credits,crs_hours,crs_sect,crs_sect_clg,crs_sect_modality,crs_sect_wiley_ind,reg_status,reg_status_date,stu_act_reg_ind
0,0,2017-05-01,Data/01_raw/EnrollmentData/CEC Graduate Regist...,5,201770,2017,Fall,Fall 2017,CEC3286,Master,...,Lecture,3,3.0,INFS 640 001,VSE,F2F,No Value,**Web Registered**,2017-04-11,Y
1,1,2017-05-01,Data/01_raw/EnrollmentData/CEC Graduate Regist...,6,201770,2017,Fall,Fall 2017,CEC3289,Master,...,Lecture,3,3.0,SWE 619 002,VSE,F2F,No Value,**Web Registered**,2017-04-11,Y
2,2,2017-05-01,Data/01_raw/EnrollmentData/CEC Graduate Regist...,10,201770,2017,Fall,Fall 2017,CEC865,Master,...,Lecture,3,3.0,CEIE 639 001,VSE,F2F,No Value,**Web Registered**,2017-04-11,Y
3,3,2017-05-01,Data/01_raw/EnrollmentData/CEC Graduate Regist...,11,201770,2017,Fall,Fall 2017,CEC865,Master,...,Lecture,3,3.0,CEIE 679 001,VSE,F2F,No Value,**Web Registered**,2017-04-11,Y
4,4,2017-05-01,Data/01_raw/EnrollmentData/CEC Graduate Regist...,12,201770,2017,Fall,Fall 2017,CEC901,Master,...,Lecture,3,3.0,SWE 645 001,VSE,F2F,No Value,**Web Registered**,2017-04-11,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323682,323682,2023-02-15,Data/01_raw/EnrollmentData/CEC Graduate Regist...,612,202310,2023,Spring,Spring 2023,CEC23433,Master,...,Internship,1-3,1.0,CEC 794 001,CEC,F2F,N,**Registered**,2023-02-09,Y
323683,323683,2023-02-15,Data/01_raw/EnrollmentData/CEC Graduate Regist...,842,202310,2023,Spring,Spring 2023,CEC26826,Master,...,Lecture,3,3.0,CS 678 002,CEC,F2F,N,**Registered**,2023-02-09,Y
323684,323684,2023-02-15,Data/01_raw/EnrollmentData/CEC Graduate Regist...,1091,202310,2023,Spring,Spring 2023,CEC27967,Master,...,Lecture,3,3.0,CS 504 006,CEC,Online,Y,**Web Registered**,2023-02-09,Y
323685,323685,2023-02-15,Data/01_raw/EnrollmentData/CEC Graduate Regist...,1278,202310,2023,Spring,Spring 2023,CEC27498,Master,...,Lecture,3,3.0,INFS 580 DL1,CEC,Online,N,**Registered**,2023-02-09,Y
323686,323686,2023-02-15,Data/01_raw/EnrollmentData/CEC Graduate Regist...,1383,202310,2023,Spring,Spring 2023,CEC28062,Master,...,Internship,1-3,1.0,CEC 794 001,CEC,F2F,N,**Registered**,2023-02-09,Y

In [23]:
# Exporting the final status of the students
df_enrollmentFinalStatus.to_csv( os.path.join("Data", "02_processed", "enrollmentFinalStatus.csv"), index=False )
df_enrollmentFinalStatus.to_pickle( os.path.join("Data", "02_processed", "enrollmentFinalStatus.pkl") )

db_enrollmentFinalStatus = ConnectDB( os.path.join("Data", "02_processed", "enrollmentFinalStatus.db") )
df_enrollmentFinalStatus.to_sql("enrollmentFinalStatus", db_enrollmentFinalStatus.connection, if_exists="replace", index=False)

59409