In [1]:
# importing the required libraries
import os
import pandas as pd
import matplotlib.pyplot as plt

os.chdir( os.path.join("..", "..", "..") )

from Code.src.modules.db_ops import *

In [2]:
# configuring the sql connection and query execution
db_enrollment = ConnectDB( os.path.join("Data", "02_processed", "enrollment4EDA.db") )

## Final Enrollment Status of all Students throughout his/her time at the University

In [3]:
df_enrollmentFinalStatus = db_enrollment.runQuery("""
    SELECT reg_term_code, reg_term_desc, stu_id, crs, MAX(reg_status_date) as final_reg_date, reg_status
    FROM enrollment4EDA
    GROUP BY reg_term_code, reg_term_desc, stu_id, crs
    ORDER BY final_reg_date;
""")

df_enrollmentFinalStatus

,reg_term_code,reg_term_desc,stu_id,crs,final_reg_date,reg_status
0,201770,Fall 2017,CEC100,AIT 622,2017-04-11 00:00:00,**Web Registered**
1,201770,Fall 2017,CEC10011,TCOM 515,2017-04-11 00:00:00,**Web Registered**
2,201770,Fall 2017,CEC10011,TCOM 631,2017-04-11 00:00:00,**Web Registered**
3,201770,Fall 2017,CEC10012,OR 538,2017-04-11 00:00:00,**Web Registered**
4,201770,Fall 2017,CEC10012,SYST 542,2017-04-11 00:00:00,**Web Registered**
...,...,...,...,...,...,...
59404,202310,Spring 2023,CEC23433,CEC 794,2023-02-09 00:00:00,**Registered**
59405,202310,Spring 2023,CEC26826,CS 678,2023-02-09 00:00:00,**Registered**
59406,202310,Spring 2023,CEC27498,INFS 580,2023-02-09 00:00:00,**Registered**
59407,202310,Spring 2023,CEC27967,CS 504,2023-02-09 00:00:00,**Web Registered**
59408,202310,Spring 2023,CEC28062,CEC 794,2023-02-09 00:00:00,**Registered**

In [4]:
# Exporting the final status of the students
df_enrollmentFinalStatus.to_csv( os.path.join("Data", "02_processed", "enrollmentFinalStatus.csv"), index=False )
df_enrollmentFinalStatus.to_pickle( os.path.join("Data", "02_processed", "enrollmentFinalStatus.pkl") )

db_enrollmentFinalStatus = ConnectDB( os.path.join("Data", "02_processed", "enrollmentFinalStatus.db") )
df_enrollmentFinalStatus.to_sql("enrollmentFinalStatus", db_enrollmentFinalStatus.connection, if_exists="replace", index=False)

59409