Rule-baased Constrained Proportional Fucking Projections

In [1]:
# importing the required libraries
import os
import pandas as pd
import matplotlib.pyplot as plt

os.chdir( os.path.join("..", "..") )

from Code.src.modules.db_ops import *
from Code.src.modules.dataManager import DataManager
from Code.src.modules.eda import *

DM = DataManager()

In [2]:
DM.get_data_info()

{'course': {'d_desc': 'Course information obtained from Web Scraping the '
                      'course catalog.',
            'd_name': 'Courses Information',
            'd_state': {'processed': {'db': 'Data\\02_processed\\course4EDA.db'}}},
 'enrollment': {'d_desc': 'Student Enrollment Status Information processed by '
                          'merging 110 CSV files obtained from Enrollment '
                          'Management at George Mason University.',
                'd_name': 'Student Enrollment Status Data',
                'd_state': {'processed': {'csv': 'Data\\02_processed\\enrollment.csv',
                                          'db': 'Data\\02_processed\\enrollment4EDA.db',
                                          'pkl': 'Data\\02_processed\\enrollment.pkl'}}},
 'enrollmentfinalstatus': {'d_desc': 'Student Final Enrollment Status '
                                     'Information processed from the '
                                     'Enrollment Data.',
                           'd_name': 'Student Final Enrollment Status Data',
                           'd_state': {'processed': {'csv': 'Data\\02_processed\\enrollmentFinalStatus.csv',
                                                     'db': 'Data\\02_processed\\enrollmentFinalStatus.db',
                                                     'pkl': 'Data\\02_processed\\enrollmentFinalStatus.pkl'}}},
 'finalsnapshot': {'d_desc': 'Final Snapshot of Student Enrollment Status '
                             'Information processed from the Enrollment Data.',
                   'd_name': 'Final Snapshot of Student Enrollment Status Data',
                   'd_state': {'processed': {'csv': 'Data\\02_processed\\final_snapshot.csv',
                                             'db': 'Data\\02_processed\\final_snapshot.db',
                                             'pkl': 'Data\\02_processed\\final_snapshot.pkl'}}},
 'professor': {'d_desc': 'Professor Information obtained from Enrollment '
                         'Management at George Mason University.',
               'd_name': 'Professor Information',
               'd_state': {'processed': {'csv': 'Data\\02_processed\\professor.csv',
                                         'db': 'Data\\02_processed\\professor4EDA.db',
                                         'pkl': 'Data\\02_processed\\professor.pkl'}}}}

In [3]:
db_FinalSnapshot = DM.get_data('FinalSnapshot', 'db', 'processed')
df_FinalSnapshot = DM.get_data('FinalSnapshot', 'pkl', 'processed')

db_EnrollmentFinalStatus = DM.get_data('EnrollmentFinalStatus', 'db', 'processed')
df_EnrollmentFinalStatus = DM.get_data('EnrollmentFinalStatus', 'pkl', 'processed')

## Exporting the data to CSV

In [8]:
# Get Course Enrollment HIstory for each course in each registration semester and student admit term
df = db_FinalSnapshot.runQuery(""" --sql
    SELECT stu_prog_desc, stu_visa, reg_status, stu_admit_term_desc, reg_term_desc, crs, COUNT(*) AS demand
    FROM FinalSnapshot
    GROUP BY
        stu_admit_term_desc, reg_term_desc, crs
    ORDER BY
        stu_admit_term_code, reg_term_code, crs
""")

df.to_csv( os.path.join('Data', '02_processed', 'RbCPP', 'FinalSnapshot.csv'), index=False)
df.to_pickle( os.path.join('Data', '02_processed', 'RbCPP', 'FinalSnapshot.pkl'))
# Exporting to SQLite Database
db = ConnectDB( os.path.join('Data', '02_processed', 'RbCPP', 'CrsDemHist.db') )
df.to_sql('FinalSnapshot', db.connection, if_exists='replace', index=False)
df

,stu_prog_desc,stu_visa,reg_status,stu_admit_term_desc,reg_term_desc,crs,demand
0,MS Civil & Infrastructure Engr,Not Relevent,**Web Registered**,Fall 2010,Fall 2017,CEIE 642,1
1,MS Electrical Engineering,Not Relevent,**Web Registered**,Fall 2010,Fall 2017,CFRS 500,1
2,MS Electrical Engineering,Not Relevent,**Web Registered**,Fall 2010,Fall 2017,ECE 795,1
3,MS Computer Forensics,Not Relevent,**Web Registered**,Fall 2011,Fall 2017,CFRS 790,1
4,MS Data Analytics Engineering,Not Relevent,**Web Registered**,Spring 2012,Fall 2017,CS 504,1
...,...,...,...,...,...,...,...
9548,MS Data Analytics Engineering,Not Relevent,**Registered**,Spring 2023,Spring 2023,SYST 573,2
9549,MS Telecommunications,F1 Visa,**Web Registered**,Spring 2023,Spring 2023,TCOM 500,3
9550,MS Telecommunications,Not Relevent,**Web Registered**,Spring 2023,Spring 2023,TCOM 514,1
9551,MS Telecommunications,Not Relevent,**Web Registered**,Spring 2023,Spring 2023,TCOM 535,3
9552,MS Telecommunications,F1 Visa,**Web Registered**,Spring 2023,Spring 2023,TCOM 616,1

In [10]:
df = db_EnrollmentFinalStatus.runQuery(""" --sql
    SELECT stu_prog_desc, stu_visa, reg_status, stu_admit_term_desc, reg_term_desc, crs, COUNT(*) AS demand
    FROM EnrollmentFinalStatus
    GROUP BY
        stu_admit_term_desc, reg_term_desc, crs
    ORDER BY
        stu_admit_term_code, reg_term_code, crs
""")
df.to_csv( os.path.join('Data', '02_processed', 'RbCPP', 'EnrollmentFinalStatus.csv'), index=False)
df.to_pickle( os.path.join('Data', '02_processed', 'RbCPP', 'EnrollmentFinalStatus.pkl'))
# Exporting to SQLite Database
df.to_sql('EnrollmentFinalStatus', db.connection, if_exists='replace', index=False)
df

,stu_prog_desc,stu_visa,reg_status,stu_admit_term_desc,reg_term_desc,crs,demand
0,MS Civil & Infrastructure Engr,Not Relevent,**Web Registered**,Fall 2010,Fall 2017,CEIE 642,1
1,MS Electrical Engineering,Not Relevent,**Web Registered**,Fall 2010,Fall 2017,CFRS 500,1
2,MS Electrical Engineering,Not Relevent,**Web Registered**,Fall 2010,Fall 2017,ECE 795,1
3,MS Computer Forensics,Not Relevent,**Web Registered**,Fall 2011,Fall 2017,CFRS 790,1
4,MS Data Analytics Engineering,Not Relevent,**Web Registered**,Spring 2012,Fall 2017,CS 504,1
...,...,...,...,...,...,...,...
11492,MS Data Analytics Engineering,Not Relevent,**Registered**,Spring 2023,Spring 2023,SYST 573,2
11493,MS Telecommunications,Not Relevent,**Web Registered**,Spring 2023,Spring 2023,TCOM 500,3
11494,MS Telecommunications,Not Relevent,**Web Registered**,Spring 2023,Spring 2023,TCOM 514,1
11495,MS Telecommunications,Not Relevent,**Web Registered**,Spring 2023,Spring 2023,TCOM 535,3
11496,MS Telecommunications,F1 Visa,**Web Registered**,Spring 2023,Spring 2023,TCOM 616,1

### Automating the RbCPP
Not really going this route though, so ðŸ’¨

In [12]:
df = db_FinalSnapshot.runQuery(""" --sql
    SELECT stu_prog_desc, stu_visa, reg_status, stu_admit_term_desc, reg_term_desc, crs, COUNT(*) AS demand
    FROM FinalSnapshot
    WHERE
        reg_status IN ("**Web Registered**", "Wait Listed", "**Registered**")
    GROUP BY
        stu_admit_term_desc, reg_term_desc, crs
    ORDER BY
        stu_admit_term_code, reg_term_code, crs
""")

df

,stu_prog_desc,stu_visa,reg_status,stu_admit_term_desc,reg_term_desc,crs,demand
0,MS Civil & Infrastructure Engr,Not Relevent,**Web Registered**,Fall 2010,Fall 2017,CEIE 642,1
1,MS Electrical Engineering,Not Relevent,**Web Registered**,Fall 2010,Fall 2017,CFRS 500,1
2,MS Electrical Engineering,Not Relevent,**Web Registered**,Fall 2010,Fall 2017,ECE 795,1
3,MS Computer Forensics,Not Relevent,**Web Registered**,Fall 2011,Fall 2017,CFRS 790,1
4,MS Data Analytics Engineering,Not Relevent,**Web Registered**,Spring 2012,Fall 2017,CS 504,1
...,...,...,...,...,...,...,...
9548,MS Data Analytics Engineering,Not Relevent,**Registered**,Spring 2023,Spring 2023,SYST 573,2
9549,MS Telecommunications,F1 Visa,**Web Registered**,Spring 2023,Spring 2023,TCOM 500,3
9550,MS Telecommunications,Not Relevent,**Web Registered**,Spring 2023,Spring 2023,TCOM 514,1
9551,MS Telecommunications,Not Relevent,**Web Registered**,Spring 2023,Spring 2023,TCOM 535,3
9552,MS Telecommunications,F1 Visa,**Web Registered**,Spring 2023,Spring 2023,TCOM 616,1

In [10]:
df_FinalSnapshot \
    .loc [:, ['stu_prog_desc', 'crs']] \
        .groupby('stu_prog_desc', as_index=False) \
            .agg({'crs': 'unique'})

,stu_prog_desc,crs
0,MENG GeoConStruct Engineering,"[CEIE 605, CEIE 639, CEIE 524, CEIE 535, CEIE ..."
1,MS Applied Info Technology,"[AIT 670, GBUS 540, AIT 671, AIT 697, AIT 622,..."
2,MS Bioengineering,"[BENG 525, BENG 541, BENG 537, BENG 550, BENG ..."
3,MS Biostatistics,"[STAT 663, STAT 665, STAT 668, STAT 654, MATH ..."
4,MS Civil & Infrastructure Engr,"[CEIE 679, COMM 637, CEIE 659, CEIE 795, CEIE ..."
5,MS Computer Engineering,"[ECE 699, ECE 681, ECE 545, ECE 642, ECE 646, ..."
6,MS Computer Forensics,"[CFRS 661, CFRS 770, CFRS 790, CFRS 664, CFRS ..."
7,MS Computer Science,"[CS 584, CS 630, CS 580, CS 795, CS 633, CS 55..."
8,MS Cyber Security Engineering,"[SYST 687, AIT 660, CFRS 767, ISA 673, AIT 670..."
9,MS Data Analytics Engineering,"[CS 504, DAEN 690, AIT 622, OR 604, ECE 535, S..."
10,MS Digital Forensics,"[CFRS 664, CFRS 760, CFRS 710, CFRS 772, CFRS ..."
11,MS Electrical Engineering,"[ECE 731, CSI 873, ECE 681, CS 580, CS 687, EC..."
12,MS Information Systems,"[INFS 640, CS 530, SWE 642, ISA 562, ISA 681, ..."
13,MS Infrmatn Security & Assrnce,"[SWE 619, CS 580, ISA 673, CFRS 761, ISA 681, ..."
14,MS Operations Research,"[OR 542, STAT 554, CS 504, OR 643, OR 635, AIT..."
15,MS Software Engineering,"[SWE 645, ISA 562, SWE 642, INFS 640, INFS 740..."
16,MS Statistical Science,"[STAT 574, STAT 652, STAT 668, STAT 665, STAT ..."
17,MS Systems Engineering,"[SWE 619, SYST 699, SYST 630, SYST 620, SYST 6..."
18,MS Telecommunications,"[TCOM 750, TCOM 660, TCOM 521, TCOM 562, TCOM ..."

In [1]:
core_courses = {
    ('MENG GeoConStruct Engineering', None) :
        ['CEIE 524', 'CEIE 525', 'CEIE 531', 'CEIE 575', 'CEIE 605'],
    ('MS Applied Info Technology','Non IT Management Concentration') :
        ['AIT 512', 'AIT 524', 'AIT 542', 'AIT 664'],
    ('MS Applied Info Technology','IT Management Concentration') :
        ['AIT 524', 'AIT 542', 'AIT 580', 'AIT 664'],
    ('MS Bioengineering', None) :
        ['BENG 520', 'BENG 521', 'BENG 541', 'BENG 526', 'BENG 537', 'BENG 538', 'BENG 501', 'BENG 514', 'BENG 517', 'BENG 601', 'BENG 602', 'STAT 535', 'STAT 560'],
    ('MS Biostatistics', None) :
        ['STAT 544', 'STAT 554', 'STAT 654', 'GCH 712', 'BENG 501', 'BINF 630', 'BENG 538', 'STAT 560', 'STAT 634', 'STAT 798'],
    ('MS Civil & Infrastructure Engr', None) :
        ['CEIE 601', 'CEIE 605'],
    ('MS Computer Engineering', None) :
        ['ECE 505', 'ECE 508', 'ECE 511', 'ECE 516', 'ECE 527', 'ECE 528', 'ECE 531', 'ECE 535', 'ECE 542', 'ECE 545', 'ECE 554', 'ECE 556', 'ECE 580', 'ECE 611', 'ECE 646', 'ECE 799'],
    # Computer Forensics Info not available
    ('MS Computer Science', None) :
        ['CS 550', 'CS 580', 'CS 584', 'CS 540', 'SWE 619', 'SWE 621', 'CS 555', 'CS 571', 'ISA 562', 'CS 583', 'CS 551'],
    ('MS Cyber Security Engineering', None) :
        ['CYSE 550', 'CYSE 570', 'CYSE 580', 'CYSE 610', 'CYSE 587', 'CYSE 690', 'CYSE 799'],
    ('MS Data Analytics Engineering', None) :
        ['AIT 580', 'STAT 515', 'OR 531', 'CS 504', 'OR 541', 'STAT 554', 'CS 584'],
    ('MS Digital Forensics', None) :
        ['DFOR 510','DFOR 660','DFOR 661','DFOR 663','DFOR 664','DFOR 670','DFOR 671','DFOR 672','DFOR 790'],
    ('MS Electrical Engineering', None) :
        ['ECE 511', 'ECE 521', 'ECE 527', 'ECE 528', 'ECE 535', 'ECE 539', 'ECE 542', 'ECE 552', 'ECE 580', 'ECE 584', 'ECE 586', 'ECE 587', 'ECE 621', 'ECE 630', 'ECE 799'],
    ('MS Information Systems', None) :
        ['COMP 502', 'CS 550', 'INFS 622', 'INFS 580', 'INFS 611'],
    ('MS Infrmatn Security & Assrnce', None) :
        ['ISA 562', 'ISA 656', 'INFS 612', 'CS 555'],
    ('MS Operations Research', None) :
        ['OR 541', 'OR 542', 'OR 568', 'OR 635'],
    ('MS Software Engineering', None) :
        ['SWE 619', 'SWE 621', 'SWE 632', 'SWE 637'],
    ('MS Statistical Science', None) :
        ['STAT 544', 'STAT 554', 'STAT 634', 'STAT 652', 'STAT 654'],
    ('MS Systems Engineering', None) :
        ['SYST 505', 'SYST 510', 'SYST 520', 'SYST 530', 'SYST 611'],
    ('MS Telecommunications', None) :
        ['TCOM 500', 'TCOM 514', 'TCOM 515', 'TCOM 535', 'TCOM 570', 'TCOM 610', 'TCOM 750']
}

final_courses = {
    ('MS Data Analytics Engineering', None) : ['DAEN 690', 'DAEN 698'],
    ('MS Information Systems', None) : ['INFS 799'],
    ('MS Computer Science', None) : ['CS 798', 'CS 799']
}